name: Daily Event Reminder

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 12:00 AM UTC
  workflow_dispatch: {}

jobs:
  send-reminders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: dev  # Ensure you're on the correct branch

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Reminder Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: node src/scripts/remindTomorrowEvents.js
